# -*- mode: python ; coding: utf-8 -*-
"""
Charlie.spec — Production PyInstaller build configuration.

SECURITY RULES:
  1. NEVER bundle: .git, .env, tests/, licensing_server/, config/api_keys.json
  2. NEVER expose: Python source (.py) in final dist (PyInstaller compiles to .pyc)
  3. NEVER include: signing secrets, private keys, payment credentials
  4. DO include: compiled bytecode, assets, icons, face model, prompt template
"""

from PyInstaller.utils.hooks import collect_data_files, collect_submodules
import os

# ── Data files to bundle ─────────────────────────────────────────────────────
datas = [
    ('actions', 'actions'),
    ('plugins', 'plugins'),
    ('core/face_model.obj', 'core'),
    ('core/assets', 'core/assets'),
    ('core/prompt.txt', 'core'),
    ('config/charlie.ico', 'config'),
    ('dashboard/static', 'dashboard/static'),
]

# Include integrity manifest if it exists (generated by build_production.py)
if os.path.exists('config/integrity_manifest.json'):
    datas.append(('config/integrity_manifest.json', 'config'))

# Include build info if it exists
if os.path.exists('config/build_info.json'):
    datas.append(('config/build_info.json', 'config'))

datas += collect_data_files('certifi')

# ── Hidden imports ───────────────────────────────────────────────────────────
hiddenimports = []
hiddenimports += collect_submodules('actions')
hiddenimports += collect_submodules('core')
hiddenimports += collect_submodules('memory')
hiddenimports += collect_submodules('dashboard')
hiddenimports += collect_submodules('plugins')
hiddenimports += collect_submodules('engine')
# AI Chat dictation imports Windows COM lazily so startup stays fast. Explicitly
hiddenimports += ['pythoncom', 'pywintypes', 'win32com', 'win32com.client']
hiddenimports += [
    'uvicorn.loops.auto',
    'uvicorn.protocols.http.auto',
    'uvicorn.protocols.websockets.auto',
    'uvicorn.lifespan.on',
]
# These files/directories MUST NOT appear in the production build.
excludes_list = [
    'licensing_server',   # Server code stays server-side
    'tests',              # Test code not for distribution
    'pytest',             # Test framework
    'unittest',           # Test framework
]

# ── Analysis ─────────────────────────────────────────────────────────────────
a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=excludes_list,
    noarchive=False,
    optimize=1,  # Bytecode optimization level 1
)

# ── Remove sensitive files from collected data ───────────────────────────────
# Post-analysis filter: strip any accidentally collected secrets
BANNED_PATTERNS = [
    'api_keys.json',
    '.env',
    '.git',
    '__pycache__',
    'licensing_server',
    'admin_panel',
    'tests',
    'test_',
    '.pyc',
    'entitlement_signing.pem',  # RSA private key
    'session_tokens.json',
    'signed_entitlement.token',
    'user_account.json',
    'license.json',
    'devices.json',
    'credentials.dat',
    '.vault',
    '.bak',
    '.sqlite3',
    'memory/profiles',
    'scratch',
    '.agent',
    '.venv',
    '.log',
]

_banned_lowers = [b.lower() for b in BANNED_PATTERNS]
filtered_datas = []
for dest, source, typecode in a.datas:
    dest_str = str(dest).lower().replace('\\', '/')
    source_str = str(source).lower().replace('\\', '/')
    if any(banned in dest_str or banned in source_str for banned in _banned_lowers):
        print(f"[BUILD SECURITY] Excluded from bundle: {dest}")
        continue
    filtered_datas.append((dest, source, typecode))
a.datas = filtered_datas

# ── PYZ Archive ──────────────────────────────────────────────────────────────
pyz = PYZ(a.pure)

# ── Executable ───────────────────────────────────────────────────────────────
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='CHARLIE',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,  # Set to your code signing identity for production
    entitlements_file=None,
    icon=['config/charlie.ico'],
    version='file_version_info.txt',  # Windows version info (generated by build script)
)

# ── Collect ──────────────────────────────────────────────────────────────────
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='CHARLIE',
)
